# Generated by Django 4.1.4 on 2022-12-19 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
