# Generated by Django 4.1.4 on 2023-01-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
        ('job_offers', '0002_application'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('employee', 'job_offer')},
        ),
    ]
