# Generated by Django 4.1.4 on 2022-12-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0002_joboffer_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='workplace',
        ),
    ]
