# Generated by Django 4.1.4 on 2022-12-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0004_alter_joboffer_salary_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='city',
            new_name='cities',
        ),
    ]
