# Generated by Django 4.1.4 on 2022-12-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0005_rename_city_joboffer_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='currency',
            field=models.CharField(blank=True, choices=[('GBP', 'GBP'), ('EUR', 'EUR'), ('CHF', 'CHF'), ('USD', 'USD'), ('PLN', 'PLN')], max_length=100),
        ),
    ]
