# Generated by Django 4.1.4 on 2022-12-17 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tags', models.CharField(choices=[('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Finances', 'Finances'), ('Engineering', 'Engineering'), ('Design', 'Design'), ('HR', 'HR'), ('Consulting', 'Consulting'), ('BI & Data', 'BI & Data'), ('SEO', 'SEO'), ('PM', 'PM'), ('Media', 'Media'), ('Support', 'Support'), ('Logistic', 'Logistic'), ('Other', 'Other')], max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('linkdin', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', "I'm actively looking for a job"), ('Open', 'Open for proposals'), ('Closed', 'Not open for proposals')], max_length=100, null=True)),
                ('about_yourself', models.TextField(blank=True, null=True)),
                ('skills', models.ManyToManyField(blank=True, to='employee.skill')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
