# Generated by Django 4.1.5 on 2023-01-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='accept_matchmaking',
            field=models.BooleanField(default=False),
        ),
    ]
