# Generated by Django 4.1.4 on 2022-12-17 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_size', models.IntegerField(default=0)),
                ('website', models.URLField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('website', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('UNPAID', 'UNPAID'), ('IN PROGRESS', 'IN PROGRESS'), ('PAID', 'PAID')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Standard', 'Standard'), ('Bussiness', 'Bussiness'), ('PRO', 'PRO'), ('Enterprise', 'Enterprise')], max_length=100)),
                ('days', models.IntegerField(default=30)),
                ('locations', models.IntegerField(default=1)),
                ('offer_raise', models.IntegerField(default=1)),
                ('promoting', models.BooleanField(default=False)),
                ('customer_care', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_day', models.DateField()),
                ('last_day', models.DateField(blank=True)),
                ('employer', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.employer')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.payment')),
            ],
        ),
    ]
