# Generated by Django 4.1.3 on 2022-11-11 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_size', models.IntegerField(default=0)),
                ('website', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('company_size', models.IntegerField(default=30)),
                ('locations', models.IntegerField(default=1)),
                ('offer_raise', models.IntegerField(default=1)),
                ('promoting', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_day', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
            ],
        ),
    ]
