# Generated by Django 4.1.4 on 2022-12-19 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        ('job_offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='job_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_offers.joboffer'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.payment'),
        ),
    ]
