# Generated by Django 4.1.3 on 2022-11-26 08:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employer',
            unique_together={('user', 'website')},
        ),
    ]
