# Generated by Django 4.1.4 on 2022-12-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_alter_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Business', 'Business'), ('Pro', 'Pro'), ('Enterprise', 'Enterprise')], max_length=100),
        ),
    ]
