# Generated by Django 4.1.3 on 2022-11-26 08:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0002_alter_employer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employer',
            unique_together={('website', 'user')},
        ),
    ]
